version: "3.9"
services:
  backend:
    image: ghcr.io/coelholimaisaias-dev/ordem-escola/backend:latest
    restart: always
    environment:
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/coelholimaisaias-dev/ordem-escola/frontend:latest
    restart: always
    ports:
      - "80:80"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
